@startuml addRoomTypeServlet

hide footbox
mainframe <b>sd</b> Add Room Type Servlet
actor User
participant "Browser" as Browser
participant ":AddRoomTypeServlet" as AddRoomTypeServlet
participant ":UseGuard" as UseGuard
participant ":GetVariable(request)" as GetVariable
participant ":RoomTypeRepository" as RoomTypeRepository
participant "Database" as Database

User ->> Browser: Click on Add room type link
activate Browser
    Browser ->> AddRoomTypeServlet: GET / AddRoomTypeServlet
    activate AddRoomTypeServlet
        AddRoomTypeServlet -->> UseGuard: UseGuard.UserAuth(): boolean
        activate UseGuard 
            UseGuard -->> AddRoomTypeServlet:return isLogin
        deactivate UseGuard

        alt not Login
            AddRoomTypeServlet -->> Browser: sendRedirect("LoginServlet")
        else check User
            AddRoomTypeServlet -->> UseGuard: UseGuard.UserRole("ADMIN"): boolean
            activate UseGuard 
                UseGuard -->> AddRoomTypeServlet:return isAdmin
            deactivate UseGuard
            alt is not Admin
                AddRoomTypeServlet -->> Browser: forward index.jsp
            else is Admin
                AddRoomTypeServlet -->> Browser: forward addRoomType.jsp           
            end
        end
    deactivate AddRoomTypeServlet

User ->> Browser: Submit form
    Browser ->> AddRoomTypeServlet : Post / AddRoomTypeServlet   
    activate AddRoomTypeServlet
        AddRoomTypeServlet ->> GetVariable: getString(String key, String label, int minLength, int maxLength, String defaultValue)
        activate GetVariable
        GetVariable ->> AddRoomTypeServlet: return roomName

        AddRoomTypeServlet ->> GetVariable: getInt(String key, String label, int minValue, int maxValue, Integer defaultValue)
        GetVariable ->> AddRoomTypeServlet: return capacity

        AddRoomTypeServlet ->> GetVariable: getInt(String key, String label, int minValue, int maxValue, Integer defaultValue)
        GetVariable ->> AddRoomTypeServlet: return acreage
        deactivate GetVariable 
    alt invalid data
        AddRoomTypeServlet -->> Browser: forward addRoomType.jsp
    else valid data
    AddRoomTypeServlet -->> RoomTypeRepository: addRoomType(RoomType roomType):boolean
        activate RoomTypeRepository
            RoomTypeRepository -->>  Database: executeQuery()
                activate Database 
                    Database ->> RoomTypeRepository: return result set
                deactivate Database
            RoomTypeRepository -->> AddRoomTypeServlet: return isSuccess
        deactivate RoomTypeRepository
        alt not success
            AddRoomTypeServlet ->> AddRoomTypeServlet: request.setAttribute("message", "Add room type failed, roomTypeId or RoomName existed")
        else success
            AddRoomTypeServlet ->> AddRoomTypeServlet: request.setAttribute("message", "Add room type successful")
        end
        AddRoomTypeServlet -->> Browser: forward addRoomType.jsp
    deactivate AddRoomTypeServlet
deactivate Browser
end

