@startuml changePasswordAccount

hide footbox
mainframe <b>sd</b> Change Password Account
actor User
participant "Browser" as Browser
participant ":ChangePasswordServlet" as ChangePasswordServlet
participant ":UseGuard" as UseGuard
participant ":GetVariable" as GetVariable
participant ":UserRepository" as UserRepository
participant ":Database" as Database

User ->> Browser: GET / ChangePasswordServlet
activate Browser
Browser -->> ChangePasswordServlet: 
activate ChangePasswordServlet
    ChangePasswordServlet -->> UseGuard
    activate UseGuard 
     UseGuard -->>  ChangePasswordServlet: return isLogin
 deactivate UseGuard
    alt not Login
        ChangePasswordServlet -->> Browser: forward login.jsp
    else Login
        ChangePasswordServlet -->> Browser: forward changePassword.jsp
    end
    
deactivate UseGuard    
deactivate ChangePasswordServlet
    
Browser -->> ChangePasswordServlet: Post/ChangePasswordServlet
activate ChangePasswordServlet
    ChangePasswordServlet ->> ChangePasswordServlet:Integer userId = (Integer) session.getAttribute("userId");
    ChangePasswordServlet ->> GetVariable: getString(String key, String label, int minLength, int maxLength, String defaultValue)
    activate GetVariable
    GetVariable ->> ChangePasswordServlet: return password
    ChangePasswordServlet ->> GetVariable: getString(String key, String label, int minLength, int maxLength, String defaultValue)
    GetVariable ->> ChangePasswordServlet: return newPassword
    ChangePasswordServlet ->> GetVariable: getString(String key, String label, int minLength, int maxLength, String defaultValue)
    GetVariable ->> ChangePasswordServlet: return newPasswordConfirm
    deactivate GetVariable

    ChangePasswordServlet ->> UserRepository: getUserByUserId(Integer id): User
    activate UserRepository
                UserRepository ->> Database: executeQuery()
                activate Database 
                    Database ->> UserRepository: return result set
                deactivate Database
        UserRepository ->> ChangePasswordServlet: return user
    deactivate UserRepository

    alt invalid password || valid confirm password
        ChangePasswordServlet ->> ChangePasswordServlet: request.setAttribute("messageError", "Update failed, please check on fields above")
        ChangePasswordServlet ->> Browser: forward changePassword.jsp
    else 
        ChangePasswordServlet ->> UserRepository: hangePassword(User u): boolean
        activate UserRepository
            UserRepository ->> Database: executeQuery()
            activate Database 
                        Database ->> UserRepository: return result set
                    deactivate Database
            UserRepository ->> ChangePasswordServlet: return isSuccess
        deactivate UserRepository
        alt not success
            ChangePasswordServlet ->> ChangePasswordServlet: request.setAttribute("messageError", "Update failed, please check on fields above")
            ChangePasswordServlet ->> Browser: forward changePassword.jsp
        else success
            ChangePasswordServlet ->> ChangePasswordServlet: request.setAttribute("message", "Update successful");
            ChangePasswordServlet ->> UseGuard: useAuth();
            activate UseGuard
                UseGuard ->> ChangePasswordServlet: return true;
            deactivate UseGuard
            ChangePasswordServlet ->> Browser: forward changePassword.jsp
        deactivate ChangePasswordServlet
    deactivate Browser
        end
    end


    
