@startuml changePasswordAccount

hide footbox
mainframe <b>sd</b> Change Password Account
actor User
participant "Browser" as Browser
participant ":ChangePasswordServlet" as ChangePasswordServlet
participant ":UseGuard" as UseGuard

User ->> Browser: GET / ChangePasswordServlet
activate Browser
Browser -->> ChangePasswordServlet: 
activate ChangePasswordServlet
    ChangePasswordServlet -->> UseGuard
    activate UseGuard 
     UseGuard -->>  ChangePasswordServlet: return isLogin
 deactivate UseGuard
    alt not Login
        ChangePasswordServlet -->> Browser: forward login.jsp
    else Login
        ChangePasswordServlet -->> Browser: forward changePassword.jsp
    end
    
deactivate UseGuard    
deactivate ChangePasswordServlet
    
Browser -->> ChangePasswordServlet: Post/ChangePasswordServlet
activate ChangePasswordServlet
activate UseGuard
    alt Valid 
     ChangePasswordServlet -->> Browser: setAttribute("message", "Update successful")
     ChangePasswordServlet -->> UseGuard: UseGuard.UseAuth()
    else Invalid
     ChangePasswordServlet -->> Browser: setAttribute("messageError", "Update failed, please check on fields above")
    end

deactivate UseGuard 
deactivate ChangePasswordServlet