hide footbox
mainframe <b>sd</b> Delete Room Servlet Servlet
actor User
participant "Browser" as Browser
participant ":DeleteRoomServlet" as DeleteRoomServlet 
participant ":UseGuard" as UseGuard
participant ":GetVariable(request)" as GetVariable
participant ":RoomRepository" as RoomRepository 
participant ":HistoryRepository" as HistoryRepository 
participant "Database" as Database

User ->> Browser: click or submit delete room
activate Browser
    Browser -->> DeleteRoomServlet: GET || POST /DeleteRoomServlet
    activate DeleteRoomServlet
        DeleteRoomServlet ->> UseGuard: UseAuth(): boolean
        activate UseGuard
            UseGuard -->> DeleteRoomServlet: return isLogin
        deactivate UseGuard
    
        alt not login 
            DeleteRoomServlet ->> Browser: sendRedirect("LoginServlet")
        else login
            DeleteRoomServlet -->> UseGuard: useGuard.useRole(User.role.ADMIN): boolean
            activate UseGuard
                UseGuard -->> DeleteRoomServlet: return isAdmin
            deactivate UseGuard
            alt not admin 
                DeleteRoomServlet ->> Browser: sendRedirect("IndexServlet")
            else admin
                DeleteRoomServlet ->> GetVariable: getInt(String key, String label, int minValue, int maxValue, Integer defaultValue): Integer
                activate GetVariable
                    GetVariable ->> DeleteRoomServlet: roomId
                deactivate GetVariable

                DeleteRoomServlet ->> RoomRepository: deleteRoom(Integer roomId): boolean
                activate RoomRepository
                    RoomRepository ->> Database: executeQuery()
                        activate Database 
                            Database ->> RoomRepository: return result set
                        deactivate Database
                    RoomRepository ->> DeleteRoomServlet: return true
                deactivate RoomRepository

                DeleteRoomServlet ->> DeleteRoomServlet: History history = new History()
                DeleteRoomServlet ->> DeleteRoomServlet: Date startDate = new Date(System.currentTimeMillis());  
                DeleteRoomServlet ->> DeleteRoomServlet: history.setRoomId(roomId);
                DeleteRoomServlet ->> DeleteRoomServlet: history.setStartDate(startDate);
                DeleteRoomServlet ->> DeleteRoomServlet: history.setMessage("We apologize for the inconvenience, this room no longer exist from now on.");

                DeleteRoomServlet ->> HistoryRepository: updateHistoryByDeleteRoom(History history): boolean
                activate HistoryRepository
                    HistoryRepository ->> Database: executeQuery()
                        activate Database 
                            Database ->> HistoryRepository: return result set
                        deactivate Database
                    HistoryRepository ->> DeleteRoomServlet: return true  
                deactivate HistoryRepository 

                DeleteRoomServlet ->> Browser: sendRedirect("EditRoomServlet")
            end
        end

        