hide footbox
mainframe <b>sd</b> Edit Room Servlet
actor User
participant "Browser" as Browser
participant ":EditRoomServlet" as EditRoomServlet
participant ":UseGuard" as UseGuard

User ->> Browser: GET /EditRoomServlet
activate Browser
Browser -->> EditRoomServlet:
activate EditRoomServlet
    EditRoomServlet -->> UseGuard
    activate UseGuard
            UseGuard -->> EditRoomServlet:return isLogin
    alt not Login
        EditRoomServlet -->> Browser: sendRedirect("LoginServlet")
    else is login
            UseGuard -->> EditRoomServlet: return isAdmin
    deactivate UseGuard
        alt not Admin
            EditRoomServlet -->> Browser: sendRedirect("IndexServlet")
        else Admin
            EditRoomServlet -->> EditRoomServlet: handleOnGet(request,response): boolean
            alt Invalid 
                EditRoomServlet -->> Browser: forward 404Page.jsp
            else Valid
                 EditRoomServlet -->> Browser: forward editRoom.jsp
            end
        end
    end
    deactivate EditRoomServlet

    