hide footbox
mainframe <b>sd</b> Edit Room Detail Servlet
actor User
participant "Browser" as Browser
participant ":EditRoomDetailServlet" as EditRoomDetailServlet 
participant ":UseGuard" as UseGuard
participant ":GetVariable(request)" as GetVariable
participant ":RoomRepository" as RoomRepository 
participant ":RoomTypeRepository" as RoomTypeRepository 
participant "Database" as Database


User -->> Browser: Click on edit room detail link 
activate Browser
    Browser -->> EditRoomDetailServlet: GET/EditRoomDetailServlet
    activate EditRoomDetailServlet
        EditRoomDetailServlet --> GetVariable: getInt(String key, String label, int minValue, int maxValue, Integer defaultValue)
        activate GetVariable
            GetVariable -->> EditRoomDetailServlet: return roomId
        deactivate GetVariable
        
        alt roomId is null 
            EditRoomDetailServlet -->> Browser: forward 404Page.jsp
        else roomId null    
            EditRoomDetailServlet ->> RoomRepository: getRoomById(roomId): Room
            activate RoomRepository
                RoomRepository ->> Database: executeQuery()
                    activate Database 
                        Database ->> RoomRepository: return result set
                    deactivate Database
                RoomRepository ->> EditRoomDetailServlet: return room
            deactivate RoomRepository

            alt room is null
                EditRoomDetailServlet -->> Browser: forward 404Page.jsp 
            else room not null    
                EditRoomDetailServlet -->> RoomTypeRepository: getAllRoomType()
                activate RoomTypeRepository
                    RoomTypeRepository ->> Database: executeQuery()
                        activate Database 
                            Database ->> RoomTypeRepository: return result set
                        deactivate Database
                    RoomTypeRepository ->> EditRoomDetailServlet: return roomTypes
                deactivate RoomTypeRepository
                EditRoomDetailServlet ->> EditRoomDetailServlet: request.setAttribute("room",room);
                EditRoomDetailServlet ->> EditRoomDetailServlet: request.setAttribute("roomTypes",roomTypes);
                EditRoomDetailServlet -->> Browser: forward editRoomDetail.jsp
            end
            deactivate EditRoomDetailServlet
        end

User ->> Browser: Submit form
    Browser -->> EditRoomDetailServlet: POST/EditRoomDetailServlet
        activate EditRoomDetailServlet
            EditRoomDetailServlet -->> UseGuard: UseGuard.UserAuth(): boolean
            activate UseGuard
                UseGuard -->> EditRoomDetailServlet: return isLogin
            deactivate UseGuard
            alt not login
                EditRoomDetailServlet -->> Browser: sendRedirect(LoginServlet)
            else Login
                EditRoomDetailServlet -->> UseGuard: useGuard.useRole(User.role.ADMIN): boolean
                activate UseGuard
                    UseGuard -->> EditRoomDetailServlet: return role
                deactivate UseGuard
                alt role not Admin
                    EditRoomDetailServlet -->> Browser: sendRedirect(IndexServlet)
                else Admin
                        EditRoomDetailServlet -->> GetVariable: getInt(String key, String label, int minValue, int maxValue, Integer defaultValue): Integer
                        activate GetVariable
                        GetVariable ->> EditRoomDetailServlet: return roomId

                        EditRoomDetailServlet -->> GetVariable: getInt(String key, String label, int minValue, int maxValue, Integer defaultValue): Integer
                        GetVariable ->> EditRoomDetailServlet: return roomTypeId

                        EditRoomDetailServlet -->> GetVariable: getFloat(String key, String label, float minValue, float maxValue, Float defaultValue): Float
                        GetVariable ->> EditRoomDetailServlet: return price

                        EditRoomDetailServlet -->> GetVariable: getFile(String key, String label, long maxSize): String
                        GetVariable ->> EditRoomDetailServlet: return imageUrl

                        EditRoomDetailServlet -->> GetVariable: getString(String key, String label, int minLength, int maxLength, String defaultValue): String
                        GetVariable ->> EditRoomDetailServlet: return description 

                        EditRoomDetailServlet -->> GetVariable: getString(String key, String label, int minLength, int maxLength, String defaultValue): String
                        GetVariable ->> EditRoomDetailServlet: return roomStatus                            
                    deactivate GetVariable
                    alt invalid data
                        EditRoomDetailServlet -->> Browser: sendRedirect(EditRoomDetailServlet + + "?roomId=" + roomId)
                    else valid data
                        EditRoomDetailServlet ->> RoomRepository: updateRoom(new Room(roomId, roomTypeId, description, price, imageUrl, roomStatus)
                        activate RoomRepository
                            RoomRepository ->> Database: executeQuery()
                            activate Database 
                                Database ->> RoomRepository: return result set
                            deactivate Database
                            RoomRepository ->> EditRoomDetailServlet: return isSuccess
                        deactivate RoomRepository
                        alt update not success
                            EditRoomDetailServlet -->> Browser:sendRedirect("EditRoomDetailServlet" + "?roomId=" + roomId)
                        else update success
                            EditRoomDetailServlet -->> Browser:sendRedirect("EditRoomServlet")
                        end
                    end
                end
            end
        deactivate EditRoomDetailServlet
    deactivate Browser
    
    
    
    
    
    
