hide footbox
mainframe <b>sd</b> Login Servlet
actor User
participant "Browser" as Browser
participant ":LoginServlet" as LoginServlet
participant ":HistoryServlet" as HistoryServlet 
participant ":UseGuard" as UseGuard
participant ":GetVariable(request)" as GetVariable

User ->> Browser: GET /HistoryServlet
activate Browser
    Browser -->> HistoryServlet: 
    activate HistoryServlet
        HistoryServlet -->> UseGuard: UseGuard.UserAuth(): boolean
        activate UseGuard
            UseGuard -->> HistoryServlet:return isLogin
        deactivate UseGuard
        alt not Login
            HistoryServlet -->> Browser: sendRedirect("LoginServlet")
        else already Login
            HistoryServlet -->> HistoryServlet: handleOnGet(request,response): boolean
            alt Invalid list
                HistoryServlet -->> Browser: forward 404Page.jsp
            else valid list
                HistoryServlet -->> Browser: forward history.jsp                
            end
                
        end  
    deactivate HistoryServlet

    Browser -->> HistoryServlet: Post/HistoryServlet
    activate HistoryServlet
        HistoryServlet -->> GetVariable: GetVariable.getString("location", "Location", 1, 15, null);
        activate GetVariable
            GetVariable -->> HistoryServlet: return location
        deactivate GetVariable
        alt localtion is null
            HistoryServlet -->> HistoryServlet: location = ""
        else location not null 
            HistoryServlet -->> HistoryServlet: location = "?status=" + location;
        end
    HistoryServlet -->> HistoryServlet: handleOnPost(request,response): boolean 
        alt Invalid
            HistoryServlet -->> Browser: forward 500Page.jsp
        else Valid 
             HistoryServlet -->> Browser: forward history.jsp + location
        end
    deactivate HistoryServlet
    deactivate Browser

             
