@startuml loginServlet

hide footbox
mainframe <b>sd</b> Login Servlet
actor User
participant "Browser" as Browser
participant ":LoginServlet" as LoginServlet
participant ":UseGuard" as UseGuard
participant ":GetVariable(request)" as GetVariable
participant ":UserRepository" as UserRepository
participant "Database" as Database


User ->> Browser: Click on login link
    activate Browser
        Browser ->> LoginServlet : GET /LoginServlet
        activate LoginServlet
            LoginServlet ->> UseGuard: UseGuard.UseAuth(): boolean
                activate UseGuard
                    UseGuard ->> LoginServlet: return isLogin
                deactivate UseGuard
            alt already login
                LoginServlet ->> Browser: Redirect /IndexServlet
            else not already login
                LoginServlet ->> Browser: forward login.jsp
            end
        deactivate LoginServlet

User ->> Browser: Submit form
    Browser ->> LoginServlet : Post /LoginServlet
    activate LoginServlet
        LoginServlet ->> GetVariable: GetVariable.getString(String key, String label, int minLength, int maxLength, String defaultValue)
            activate GetVariable
                GetVariable ->> LoginServlet: return username
                GetVariable ->> LoginServlet: return password
            deactivate GetVariable
        alt invalid data 
            LoginServlet ->> Browser: forward login.jsp
        else valid data
            LoginServlet ->> UserRepository: getUserByUsername(String username):User
                activate UserRepository
                    UserRepository ->> Database: executeQuery()
                        activate Database 
                            Database ->> UserRepository: return result set
                        deactivate Database
                    UserRepository ->> LoginServlet: return User
                deactivate UserRepository
            alt not exist user
                LoginServlet ->> Browser: forward login.jsp
            else exist user
                alt invalid password
                    LoginServlet ->> Browser: forward login.jsp
                else valid password
                    LoginServlet ->> LoginServlet : HttpSession.setAttribute("userRole", user.getRole()):void
                    LoginServlet ->> LoginServlet : HttpSession.setAttribute("userId", user.getUserId()):void
                    LoginServlet ->> LoginServlet : HttpSession.setAttribute("fullname", user.getFullname()):void
                    LoginServlet ->> Browser: Redirect /IndexServlet
    deactivate LoginServlet                     
    deactivate Browser
                end
                
            end

        end
