@startuml loginAccount

hide footbox
mainframe <b>sd</b> Login Account
actor User
participant "Browser" as Browser
participant ":LogoutServlet" as LogoutServlet
participant ":GetParam" as GetParam
participant ":UserDAO" as UserDao
participant "Database" as DB


User ->> Browser: Click on login link
activate Browser

Browser ->> LoginController: GET /LoginController
activate LoginController
LoginController -->> Browser: forward login.jsp
deactivate LoginController



User ->> Browser: Submit on login form
    Browser ->> LoginController: POST /LoginController
    activate LoginController
    LoginController ->> GetParam: getStringParam(HttpServletRequest request, String field, String label, int min, int max,String defaultValue):String
    activate GetParam
    GetParam -->> LoginController: return username, password
    deactivate GetParam
alt invalid data
    LoginController -->> Browser: forward login.jsp
else valid data
    LoginController ->> UserDao: getOneUserByUsername(String username): User
    activate UserDao
    UserDao ->> DB: executeQuery()
    activate DB
    DB -->> UserDao: Return result set
    deactivate DB
    UserDao -->> LoginController: User
    deactivate UserDao
    deactivate GetParam
    alt Not found user
        LoginController -->> Browser: forward login.jsp
    else Found user
        LoginController ->> LoginController: comparePassword(String inputPassword, String databasePassword, int key): boolean
        alt Incorrect password
            LoginController -->> Browser: forward login.jsp
        else Correct password
            LoginController ->> LoginController: HttpSession.setAttribute(String arg0, Object arg1): void
            LoginController -->> Browser: Redirect /IndexController 
            deactivate LoginController
            deactivate Browser
        end
    end       
end
@enduml