hide footbox
mainframe <b>sd</b> Remove Cart Item Servlet
actor User
participant "Browser" as Browser
participant ":RemoveCartItemServlet" as RemoveCartItemServlet 
participant ":GetVariable" as GetVariable

User -->> Browser: Click Remove Cart Item Link
activate Browser
    Browser -->> RemoveCartItemServlet: GET || POST /RemoveCartItemServlet
    activate RemoveCartItemServlet
        RemoveCartItemServlet -->> GetVariable: getInt(String key, String label, int minValue, int maxValue, Integer defaultValue): Integer
        activate GetVariable
            GetVariable -->> RemoveCartItemServlet: return index
        deactivate GetVariable
        alt index == null
            RemoveCartItemServlet -->> Browser: sendRedirect(CartServlet)
        else index not null
            RemoveCartItemServlet ->> RemoveCartItemServlet: ArrayList<CartItem> cart = (ArrayList<CartItem>) session.getAttribute("cart");   
            RemoveCartItemServlet-->> RemoveCartItemServlet: cart.remove(cart.get(index))
            RemoveCartItemServlet ->> RemoveCartItemServlet: session.setAttribute("cart", cart);   
            RemoveCartItemServlet -->> Browser: sendRedirect(CartServlet)
        end
    deactivate RemoveCartItemServlet
deactivate Browser

