@startuml users

hide footbox
mainframe <b>sd</b> Users Servlet
actor User
participant "Browser" as Browser
participant ":UsersServlet" as UsersServlet
participant ":UseGuard" as UseGuard
participant ":UserRepository" as UserRepository
participant "Database" as Database

User -->> Browser: click user info link
activate Browser    
    Browser -->> UsersServlet :  GET/UserInfoServlet
    activate UsersServlet
        UsersServlet ->> UseGuard: useAuth(): boolean
        activate UseGuard
            UseGuard ->> UsersServlet: return isLogin    
        deactivate UseGuard
    alt not login    
        UsersServlet ->> Browser: sendRedirect("IndexServlet")
    else login
        UsersServlet ->> UseGuard: useRole(UserRole.role role): boolean
        activate UseGuard
            UseGuard ->> UsersServlet: return isAdmin  
        deactivate UseGuard
        alt not Admin
            UsersServlet ->> Browser: sendRedirect("IndexServlet")
        else admin
            UsersServlet ->> UserRepository: getAllUserList():  ArrayList<User>
            activate UserRepository
                UserRepository -->> Database: executeQuery()
                activate Database
                    Database ->> UserRepository: return result set
                deactivate Database
            UserRepository -->> UsersServlet: return users
        deactivate UserRepository

        UsersServlet ->> UsersServlet: request.setAttribute("users", users)

        UsersServlet ->> Browser: forward users.jsp
    deactivate UsersServlet
deactivate Browser
        end
    end
    deactivate UsersServlet