@startuml loginServlet
hide footbox
mainframe <b>sd</b> User Histories Servlet
actor User
participant "Browser" as Browser
participant ":UserHistoriesServlet" as UserHistoriesServlet
participant ":UseGuard" as UseGuard
participant ":GetVariable(request)" as GetVariable
participant ":HistoryService" as HistoryService
participant ":HistoryRepository" as HistoryRepository
participant "Database" as Database


User ->> Browser: Click on user histories link
    activate Browser
        Browser ->> UserHistoriesServlet : GET /LoginServlet
        activate UserHistoriesServlet
            UserHistoriesServlet ->> GetVariable: getInt(String key, String label, int minValue, int maxValue, Integer defaultValue) 
            activate GetVariable
                GetVariable ->> UserHistoriesServlet: userId
            deactivate GetVariable
        alt userId is null
            UserHistoriesServlet ->> Browser: forward 404Page.jsp
        else userid not null
            UserHistoriesServlet ->> GetVariable:getDate(String key, String label, Date defaultValue)
            activate GetVariable
            GetVariable ->> UserHistoriesServlet: return startDate 

            UserHistoriesServlet ->> GetVariable:getDate(String key, String label, Date defaultValue)
            GetVariable ->> UserHistoriesServlet: return endDate 
            deactivate GetVariable

            UserHistoriesServlet ->> HistoryRepository: 
            activate HistoryRepository
                    HistoryRepository ->> Database: executeQuery()
                        activate Database 
                            Database ->> HistoryRepository: return result set
                        deactivate Database
                    HistoryRepository ->> UserHistoriesServlet: return User
            deactivate HistoryRepository

            alt startDate not null and endDate not null
                UserHistoriesServlet ->> HistoryService: filterHistoryByDate(ArrayList<History> histories, Date startDate, Date endDate): ArrayList<History>
                activate HistoryService
                    HistoryService ->> UserHistoriesServlet: return list
                UserHistoriesServlet ->> UserHistoriesServlet:  request.setAttribute("startDate", startDate.toString());
                UserHistoriesServlet ->> UserHistoriesServlet:  request.setAttribute("endDate", endDate.toString());

                UserHistoriesServlet ->> HistoryService: isValidDateInput(Date inputCheckIn, Date inputCheckOut): boolean
                HistoryService ->> UserHistoriesServlet: return isValid
                deactivate HistoryService

                alt not valid
                    UserHistoriesServlet ->> UserHistoriesServlet: list.clear()
                    UserHistoriesServlet ->> UserHistoriesServlet: request.setAttribute("checkOutError", "End date must greater than start date")
                end

            end
            UserHistoriesServlet ->> UserHistoriesServlet: request.setAttribute("list", list)
            UserHistoriesServlet ->> UserHistoriesServlet: request.setAttribute("userId", userId)

            UserHistoriesServlet ->> Browser: forward userHistories.jsp
        deactivate UserHistoriesServlet
    deactivate Browser
        end