@startuml indexServlet

hide footbox
mainframe <b>sd</b> Index Servlet
actor User
participant "Browser" as Browser
participant ":IndexServlet" as IndexServlet


User ->> Browser: Click on index link
    activate Browser
        Browser ->> IndexServlet : GET /IndexServlet
        activate IndexServlet
            IndexServlet ->> Browser: forword index.jsp
        deactivate IndexServlet
    deactivate Browser

